var today = new Date();
var todayDateString = today.getFullYear() + '-' + ('0' + (today.getMonth() + 1)).slice(-2)  + '-' + ('0' + today.getDate()).slice(-2);

$("#identitetStyrkt").val("Anhörig").change();
$("#land").val("Mordor").change();
$("#dodsdatumSakertNo").prop("checked", true).trigger("click");
$("#dodsdatum-year").val("1900").change();
$("#dodsdatum-month").val("01").change();
$("#dodsdatum-day").val("01").change();
$("#form_antraffatDodDatum > div > div:nth-child(2) > span > span > input").val(todayDateString).change();
$("#dodsplatsKommun").val("Vattnadal").change();
$("#dodsplatsBoende-ORDINART_BOENDE").prop("checked", true).trigger("click");
$("#barnNo").prop("checked", true).trigger("click");
$("#orsak--beskrivning").val("Hjärtat slutade slå.").change();
$("#orsak--datum").val(todayDateString).change();
$("#orsak--specifikation > div.ui-select-match > span").click();
$("#ui-select-choices-row-17-2 > span > span").click();
$("[id$=-3]").click();
$("#orsak-0-beskrivning").val("Att hjärtat stannade.").change();
$("#orsak-0-datum").val(todayDateString).change();
$("#orsak-0-specifikation > div.ui-select-match > span").click();
$("#ui-select-choices-row-62-2 > span > span").click();
$("[id$=-1]").click();
$("#orsak-1-beskrivning").val("Något annat.").change();
$("#orsak-1-datum").val(todayDateString).change();
$("#orsak-1-specifikation > div.ui-select-match > span").click();
$("#ui-select-choices-row-63-1 > span > span").click();
$("[id$=-2]").click();
$("#orsak-2-beskrivning").val("Ytterligare något annat.").change();
$("#orsak-2-datum").val(todayDateString).change();
$("#orsak-2-specifikation > div.ui-select-match > span").click();
$("#ui-select-choices-row-63-3 > span > span").click();
$("[id$=-2]").click();
$("#orsak-multi-0-beskrivning").val("Duengefeber").change();
