var today = new Date();
var todayDateString = today.getFullYear() + "-" + ("0" + (today.getMonth() + 1)).slice(-2)  + "-" + ("0" + today.getDate()).slice(-2);

$('#intygAvser\\.kategorier-AM').click();
$('#intygAvser\\.kategorier-A1').click();
$('#intygAvser\\.kategorier-A2').click();
$('#intygAvser\\.kategorier-A').click();
$('#intygAvser\\.kategorier-B').click();
$('#intygAvser\\.kategorier-BE').click();
$('#intygAvser\\.kategorier-TRAKTOR').click();
$('#intygAvser\\.kategorier-C1').click();
$('#intygAvser\\.kategorier-C1E').click();
$('#intygAvser\\.kategorier-C').click();
$('#intygAvser\\.kategorier-CE').click();
$('#intygAvser\\.kategorier-D1').click();
$('#intygAvser\\.kategorier-D1E').click();
$('#intygAvser\\.kategorier-D').click();
$('#intygAvser\\.kategorier-DE').click();
$('#intygAvser\\.kategorier-TAXI').click();
$('#identitetStyrktGenom\\.typ-ID_KORT').prop('checked', true).trigger('click');
$('#allmant-diabetesDiagnosAr').val('2010').change();
$('#allmant\\.typAvDiabetes-ANNAN').prop('checked', true).trigger('click');
$('#allmant-beskrivningAnnanTypAvDiabetes').val('Hej hopp').change();
$('#allmant-behandling-endastKost').click();
$('#allmant-behandling-tabletter').click();
$('#allmant-behandling-tablettRiskHypoglykemiYes').click();
$('#allmant-behandling-insulin').click();
$('#allmant-behandling-insulinSedanAr').val('2015').change();
$('#allmant-behandling-annanBehandling').click();
$('#allmant-behandling-annanBehandlingBeskrivning').val('1abcåäö--10ABCÅÄÖ--20 --------30-------40').change(); 
$('#hypoglykemier-sjukdomenUnderKontrollYes').prop('checked', true).trigger('click');
$('#hypoglykemier-nedsattHjarnfunktionYes').prop('checked', true).trigger('click');
$('#hypoglykemier-forstarRiskerYes').prop('checked', true).trigger('click');
$('#hypoglykemier-fortrogenMedSymptomYes').prop('checked',true).trigger('click');
$('#hypoglykemier-saknarFormagaVarningsteckenYes').prop('checked',true).trigger('click');
$('#hypoglykemier-kunskapLampligaAtgarderYes').prop('checked', true).trigger('click');
$('#hypoglykemier-egenkontrollBlodsockerYes').prop('checked', true).trigger('click');
$('#hypoglykemier-aterkommandeSenasteAretYes').prop('checked', true).trigger('click');
$('#datepicker_hypoglykemier\\.aterkommandeSenasteTidpunkt').val(todayDateString).change();
$('#hypoglykemier-aterkommandeSenasteKvartaletYes').prop('checked', true).trigger('click');
$('#datepicker_hypoglykemier\\.senasteTidpunktVaken').val(todayDateString).change();
$('#hypoglykemier-forekomstTrafikYes').prop('checked', true).trigger('click');
$('#datepicker_hypoglykemier\\.forekomstTrafikTidpunkt').val(todayDateString).change();
$('#synfunktion-misstankeOgonsjukdomYes').prop('checked', true).trigger('click');
$('#syn-separatOgonlakarintygNo').prop('checked', true).trigger('click');
$('#synfunktion-ogonbottenFotoSaknasYes').prop('checked', true).trigger('click');
$('#synfunktion-hoger-utanKorrektion').val('0,0').change();
$('#synfunktion-vanster-utanKorrektion').val('0,1').change();
$('#synfunktion-binokulart-utanKorrektion').val('2,0').change();
$('#synfunktion-hoger-medKorrektion').val('1,9').change();
$('#synfunktion-vanster-medKorrektion').val('1,0').change();
$('#synfunktion-binokulart-medKorrektion').val('1,8').change();
$('#ovrigt').val('!#$%&*+,-./0123456789:<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^)_`abcdefghijklmnopqrstuvwxyz{|}~€‚ƒ„…†‡ˆ‰Š‹ŒŽ‘’“”•–—˜™šžŸ ¡¢£¤¥¦§¨©ª«¬­¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ)').change();
$('#bedomning\\.uppfyllerBehorighetskrav-C1').click();
$('#bedomning\\.uppfyllerBehorighetskrav-C1E').click();
$('#bedomning\\.uppfyllerBehorighetskrav-C').click();
$('#bedomning\\.uppfyllerBehorighetskrav-CE').click();
$('#bedomning\\.uppfyllerBehorighetskrav-D1').click();
$('#bedomning\\.uppfyllerBehorighetskrav-D1E').click();
$('#bedomning\\.uppfyllerBehorighetskrav-D').click();
$('#bedomning\\.uppfyllerBehorighetskrav-DE').click();
$('#bedomning\\.uppfyllerBehorighetskrav-TAXI').click();
$('#bedomning\\.uppfyllerBehorighetskrav-AM').click();
$('#bedomning\\.uppfyllerBehorighetskrav-A1').click();
$('#bedomning\\.uppfyllerBehorighetskrav-A2').click();
$('#bedomning\\.uppfyllerBehorighetskrav-A').click();
$('#bedomning\\.uppfyllerBehorighetskrav-B').click();
$('#bedomning\\.uppfyllerBehorighetskrav-BE').click();
$('#bedomning\\.uppfyllerBehorighetskrav-TRAKTOR').click();
$('#bedomning-lampligtInnehavYes').prop('checked', true).trigger('click');
$('#bedomning-borUndersokasBeskrivning').val('1abcåäö--10ABCÅÄÖ --20--------30-------40').change();
$('#bedomning-lakareSpecialKompetens').val('1abcåäö--10ABCÅÄ Ö--20--------30-------40').change();