$("#intygAvser\\.kategorier-AM").click();
$("#intygAvser\\.kategorier-A1").click();
$("#intygAvser\\.kategorier-A2").click();
$("#intygAvser\\.kategorier-A").click();
$("#intygAvser\\.kategorier-B").click();
$("#intygAvser\\.kategorier-BE").click();
$("#intygAvser\\.kategorier-TRAKTOR").click();
$("#intygAvser\\.kategorier-C1").click();
$("#intygAvser\\.kategorier-C1E").click();
$("#intygAvser\\.kategorier-C").click();
$("#intygAvser\\.kategorier-CE").click();
$("#intygAvser\\.kategorier-D1").click();
$("#intygAvser\\.kategorier-D1E").click();
$("#intygAvser\\.kategorier-D").click();
$("#intygAvser\\.kategorier-DE").click();
$("#intygAvser\\.kategorier-TAXI").click();
$("#identitetStyrktGenom\\.typ-ID_KORT").prop("checked", true).trigger("click");
$("#allmant-diabetesDiagnosAr").val("2010").change();
$('#allmant\\.typAvDiabetes-TYP2').prop("checked", true).trigger("click");
$("#allmant-behandling-endastKost").click();
$("#allmant-behandling-tabletter").click();
$("#allmant-behandling-tablettRiskHypoglykemiYes").click();
$("#allmant-behandling-insulin").click();
$("#allmant-behandling-insulinSedanAr").val("2015").change();
$("#allmant-behandling-annanBehandling").click();
$("#allmant-behandling-annanBehandlingBeskrivning").val("1abcåäö--10ABCÅÄÖ--20 --------30-------40").change();  //sista raden som fixats
$("#hypoglykemier-kunskapOmAtgarderNo").prop("checked", true).trigger("click");
$("#hypoglykemier-teckenNedsattHjarnfunktionYes").prop("checked", true).trigger("click");
$("#hypoglykemier-egenkontrollBlodsockerYes").prop("checked", true).trigger("click");
$("#hypoglykemier-allvarligForekomstVakenTidYes").prop("checked",true).trigger("click");
$("#datepicker_hypoglykemier.allvarligForekomstVakenTidObservationstid".replace(".","\\.")).val("2018-04-20").change();  //bort med punkter i id
$("#hypoglykemier-saknarFormagaKannaVarningsteckenYes").prop("checked", true).trigger("click");
$("#hypoglykemier-allvarligForekomstYes").prop("checked", true).trigger("click");
$("#hypoglykemier-allvarligForekomstBeskrivning").prop("value","1abcåäö--10ABCÅÄÖ--20- -------30").change();
$("#hypoglykemier-allvarligForekomstTrafikenYes").prop("checked", true).trigger("click");
$("#hypoglykemier-allvarligForekomstTrafikBeskrivning").prop("value","1abcåäö-- 10ABCÅÄÖ--20--------30").change();
$("#syn-separatOgonlakarintygNo").prop("checked", true).trigger("click");
$("#syn-synfaltsprovningUtanAnmarkningNo").prop("checked", true).trigger("click");
$("#syn-hoger-utanKorrektion").val("0,0").change();
$("#syn-vanster-utanKorrektion").val("0,1").change();
$("#syn-binokulart-utanKorrektion").val("2,0").change();
$("#syn-hoger-medKorrektion").val("1,9").change();
$("#syn-vanster-medKorrektion").val("1,0").change();
$("#syn-binokulart-medKorrektion").val("1,8").change();
$("#syn-diplopiYes").prop("checked", true).trigger("click");
$("#bedomning-AM").click();
$("#bedomning-A1").click();
$("#bedomning-A2").click();
$("#bedomning-A").click();
$("#bedomning-B").click();
$("#bedomning-BE").click();
$("#bedomning-TRAKTOR").click();
$("#bedomning-C1").click();
$("#bedomning-C1E").click();
$("#bedomning-C").click();
$("#bedomning-CE").click();
$("#bedomning-D1").click();
$("#bedomning-D1E").click();
$("#bedomning-D").click();
$("#bedomning-DE").click();
$("#bedomning-TAXI").click();
$("#bedomning-lamplighetInnehaBehorighetYes").prop("checked", true).trigger("click");
$("#kommentar").val("1abcåäö--10ABCÅÄÖ --20--------30-------40").change();
$("#bedomning-lakareSpecialKompetens").val("1abcåäö--10ABCÅÄ Ö--20--------30-------40").change();