var today = new Date();
var todayDateString = today.getFullYear() + "-" + ("0" + (today.getMonth() + 1)).slice(-2)  + "-" + ("0" + today.getDate()).slice(-2);

$("#intygAvser\\.kategorier-IAV11").click();
$("#intygAvser\\.kategorier-IAV12").click();
$("#intygAvser\\.kategorier-IAV13").click();
$("#intygAvser\\.kategorier-IAV14").click();
$("#intygAvser\\.kategorier-IAV15").click();
$("#intygAvser\\.kategorier-IAV16").click();
$("#intygAvser\\.kategorier-IAV17").click();
$("#intygAvser\\.kategorier-IAV1").click();
$("#intygAvser\\.kategorier-IAV2").click();
$("#intygAvser\\.kategorier-IAV3").click();
$("#intygAvser\\.kategorier-IAV4").click();
$("#intygAvser\\.kategorier-IAV5").click();
$("#intygAvser\\.kategorier-IAV6").click();
$("#intygAvser\\.kategorier-IAV7").click();
$("#intygAvser\\.kategorier-IAV8").click();
$("#intygAvser\\.kategorier-IAV9").click();
$('#identitetStyrktGenom\\.typ-IDK1').prop('checked', true).trigger('click');
$('#allmant-diabetesDiagnosAr').val('2010').change();
$('#allmant\\.typAvDiabetes-ANNAN').prop('checked', true).trigger('click');
$('#allmant-beskrivningAnnanTypAvDiabetes').val('Hej hopp').change();
$('#allmant-behandling-endastKost').click();
$('#allmant-behandling-tabletter').click();
$('#allmant-behandling-tablettRiskHypoglykemiYes').prop('checked', true).trigger('click');
$('#allmant-behandling-insulin').click();
$('#allmant-behandling-insulinSedanAr').val('2015').change();
$('#allmant-behandling-annanBehandling').click();
$('#allmant-behandling-annanBehandlingBeskrivning').val('HEJ1abcåäö--10ABCÅÄÖ--20 --------30-------40').change(); 
$('#allmant-behandling-riskHypoglykemiYes').prop('checked', true).trigger('click');
$('#hypoglykemier-egenkontrollBlodsockerYes').prop('checked', true).trigger('click');
$('#hypoglykemier-nedsattHjarnfunktionYes').prop('checked', true).trigger('click');
$('#hypoglykemier-sjukdomenUnderKontrollYes').prop('checked', true).trigger('click');
$('#hypoglykemier-formagaVarningsteckenYes').prop('checked',true).trigger('click');
$('#hypoglykemier-aterkommandeSenasteAretYes').prop('checked', true).trigger('click');
$('#datepicker_hypoglykemier\\.aterkommandeSenasteTidpunkt').val(todayDateString).change();
$('#hypoglykemier-aterkommandeSenasteKvartaletYes').prop('checked', true).trigger('click');
$('#datepicker_hypoglykemier\\.senasteTidpunktVaken').val(todayDateString).change();
$('#hypoglykemier-forekomstTrafikYes').prop('checked', true).trigger('click');
$('#datepicker_hypoglykemier\\.forekomstTrafikTidpunkt').val(todayDateString).change();
$('#synfunktion-misstankeOgonsjukdomYes').prop('checked', true).trigger('click');
$('#syn-separatOgonlakarintygNo').prop('checked', true).trigger('click');
$('#synfunktion-ogonbottenFotoSaknasYes').prop('checked', true).trigger('click');
$('#synfunktion-hoger-utanKorrektion').val('0,0').change();
$('#synfunktion-vanster-utanKorrektion').val('0,1').change();
$('#synfunktion-binokulart-utanKorrektion').val('2,0').change();
$('#synfunktion-hoger-medKorrektion').val('1,9').change();
$('#synfunktion-vanster-medKorrektion').val('1,0').change();
$('#synfunktion-binokulart-medKorrektion').val('1,8').change();
$('#ovrigt').val("Lite vanlig hederlig text.").change();
$("#bedomning\\.uppfyllerBehorighetskrav-VAR12").click();
$("#bedomning\\.uppfyllerBehorighetskrav-VAR13").click();
$("#bedomning\\.uppfyllerBehorighetskrav-VAR14").click();
$("#bedomning\\.uppfyllerBehorighetskrav-VAR15").click();
$("#bedomning\\.uppfyllerBehorighetskrav-VAR16").click();
$("#bedomning\\.uppfyllerBehorighetskrav-VAR17").click();
$("#bedomning\\.uppfyllerBehorighetskrav-VAR18").click();
$("#bedomning\\.uppfyllerBehorighetskrav-VAR1").click();
$("#bedomning\\.uppfyllerBehorighetskrav-VAR2").click();
$("#bedomning\\.uppfyllerBehorighetskrav-VAR3").click();
$("#bedomning\\.uppfyllerBehorighetskrav-VAR4").click();
$("#bedomning\\.uppfyllerBehorighetskrav-VAR5").click();
$("#bedomning\\.uppfyllerBehorighetskrav-VAR6").click();
$("#bedomning\\.uppfyllerBehorighetskrav-VAR7").click();
$("#bedomning\\.uppfyllerBehorighetskrav-VAR8").click();
$("#bedomning\\.uppfyllerBehorighetskrav-VAR9").click();
$('#bedomning-lampligtInnehavYes').prop('checked', true).trigger('click');
$('#bedomning-borUndersokasBeskrivning').val('1abcåäö--10ABCÅÄÖ --20--------30-------40').change();
$('#bedomning-lakareSpecialKompetens').val('1abcåäö--10ABCÅÄ Ö--20--------30-------40').change();