$("#intygAvser\\.korkortstyp-AM").click();
$("#intygAvser\\.korkortstyp-A1").click();
$("#intygAvser\\.korkortstyp-A2").click();
$("#intygAvser\\.korkortstyp-A").click();
$("#intygAvser\\.korkortstyp-B").click();
$("#intygAvser\\.korkortstyp-BE").click();
$("#intygAvser\\.korkortstyp-TRAKTOR").click();
$("#intygAvser\\.korkortstyp-C1").click();
$("#intygAvser\\.korkortstyp-C1E").click();
$("#intygAvser\\.korkortstyp-C").click();
$("#intygAvser\\.korkortstyp-CE").click();
$("#intygAvser\\.korkortstyp-D1").click();
$("#intygAvser\\.korkortstyp-D1E").click();
$("#intygAvser\\.korkortstyp-D").click();
$("#intygAvser\\.korkortstyp-DE").click();
$("#intygAvser\\.korkortstyp-TAXI").click();
$("#vardkontakt\\.idkontroll-ID_KORT").prop("checked", true).trigger("click");
$("#diabetes-observationsperiod").val("2010").change();
$('#diabetes\\.diabetestyp-DIABETES_TYP_2').click();
$("#diabetes-endastKost").click();
$("#diabetes-tabletter").click();
$("#diabetes-insulin").click();
$("#diabetes-insulinBehandlingsperiod").val("2015").change();
$("#diabetes-annanBehandlingBeskrivning").val("1abcåäö--10ABCÅÄÖ--20 --------30-------40").change();
$("#hypoglykemier-kunskapOmAtgarderNo").click();
$("#hypoglykemier-teckenNedsattHjarnfunktionYes").click();
$("#hypoglykemier-egenkontrollBlodsockerNo").click();
$("#hypoglykemier-allvarligForekomstVakenTidYes").prop("checked",true).trigger("click");
$("#datepicker_hypoglykemier.allvarligForekomstVakenTidObservationstid".replace(".","\\.")).val("2018-04-20").change();  //bort med punkter i id
$("#hypoglykemier-saknarFormagaKannaVarningsteckenYes").click();
$("#hypoglykemier-allvarligForekomstYes").click();
$("#hypoglykemier-allvarligForekomstBeskrivning").val("1abcåäö--10ABCÅÄÖ--20- -------30-------40").change();
$("#hypoglykemier-allvarligForekomstTrafikenYes").click();
$("#allvarligForekomstTrafikBeskrivning").val("1abcåäö-- 10ABCÅÄÖ--20--------30-------40").change();
$("#syn-separatOgonlakarintygNo").click();
$("#syn-synfaltsprovningUtanAnmarkningNo").click();
$("#syn-hoger-utanKorrektion").val("0,0").change();
$("#syn-vanster-utanKorrektion").val("0,1").change();
$("#syn-binokulart-utanKorrektion").val("2,0").change();
$("#syn-hoger-medKorrektion").val("1,9").change();
$("#syn-vanster-medKorrektion").val("1,0").change();
$("#syn-binokulart-medKorrektion").val("1,8").change();
$("#syn-diplopiYes").click();
$("#bedomning-AM").click();
$("#bedomning-A1").click();
$("#bedomning-A2").click();
$("#bedomning-A").click();
$("#bedomning-B").click();
$("#bedomning-BE").click();
$("#bedomning-TRAKTOR").click();
$("#bedomning-C1").click();
$("#bedomning-C1E").click();
$("#bedomning-C").click();
$("#bedomning-CE").click();
$("#bedomning-D1").click();
$("#bedomning-D1E").click();
$("#bedomning-D").click();
$("#bedomning-DE").click();
$("#bedomning-TAXI").click();
$("#bedomning-lamplighetInnehaBehorighetYes").click();
$("#kommentar").val("1abcåäö--10ABCÅÄÖ --20--------30-------40").change();
$("#bedomning-lakareSpecialKompetens").val("1abcåäö--10ABCÅÄ Ö--20--------30-------40").change();