$("#typcheck0").click();
$("#typcheck1").click();
$("#typcheck2").click();
$("#typcheck3").click();
$("#typcheck4").click();
$("#typcheck5").click();
$("#typcheck6").click();
$("#typcheck7").click();
$("#typcheck8").click();
$("#typcheck9").click();
$("#identity2").focus();
$("#identity2").click();
/*$("#identity2").focus();
$("#identity2").click();*/
$("#synay").focus();
$("#synay").click();
$("#synbn").focus();
$("#synbn").click();
$("#syncy").focus();
$("#syncy").click();
$("#syndy").focus();
$("#syndy").click();
$("#synen").focus();
$("#synen").click();
$("#synHogerOgaUtanKorrektion").val("0,0").change();
$("#synHogerOgaMedKorrektion").val("0,2").change();
$("#synHogerOgaKontaktlins").click();
$("#synVansterOgaUtanKorrektion").val("0,0").change();
$("#synVansterOgaMedKorrektion").val("0,2").change();
$("#synVasterOgaKontaktlins").click();
$("#synBinokulartUtanKorrektion").val("0,0").change();
$("#synBinokulartMedKorrektion").val("0,2").change();
$("#dioptrier").click();
$("#horselbalansay").focus().click();
$("#horselbalansby").focus().click();
$("#funktionsnedsattningay").focus().click();
$("#funktionsnedsattning").val("Epilepsi").change();
$("#funktionsnedsattningbn").focus().click();
$("#hjartkarlay").focus().click();
$("#hjartkarlbn").focus().click();
$("#hjartkarlcy").focus().click();
$("#beskrivningRiskfaktorer").val("Kranskärlproblem").change();
$("#diabetesay").focus().click();
$("#diabetestyp1").focus().click();
$("#neurologiay").focus().click();
$("#medvetandestorningay").focus().click();
$("#beskrivningMedvetandestorning").val("26/6 för mycket TV-spel").change();
$("#njuraray").focus().click();
$("#kognitivtan").focus().click();
$("#somnvakenhetForm > span:nth-child(2) > span:nth-child(2) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(2) > input:nth-child(1)").focus().click();
$("#narkotikalakemedela").focus().click();
$("#narkotikaLakemedelForm > span:nth-child(2) > span:nth-child(2) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(2) > input:nth-child(1)").focus().click();
$("#narkotikaLakemedelForm > span:nth-child(2) > span:nth-child(2) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2) > label:nth-child(3) > input:nth-child(1)").focus().click();
$("#narkotikaLakemedelForm > span:nth-child(2) > span:nth-child(2) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(5) > td:nth-child(1) > input:nth-child(1)").focus().click();
$("#beskrivningNarkotikalakemedel").val("Ibuprofen och många.").change();
$("#psykiskta").focus().click();
$("#utvecklingsstorningForm > span:nth-child(2) > span:nth-child(2) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(2) > input:nth-child(1)").focus().click();
$("#utvecklingsstorningForm > span:nth-child(2) > span:nth-child(2) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(1) > input:nth-child(1)").focus().click();
$("#sjukhusvarda").focus().click();
$("#tidpunkt").val("2016-09-21").change();
$("#vardinrattning").val("Smultronet").change();
$("#anledning").val("Nageltrång").change();
$("#medicineringa").focus().click();
$("#beskrivningMedicinering").val("Alvedon.").change();
$("#kommentar").val("Inga kommentarer.").change();
$("#behorighet_bedomning").focus().click();
$("#korkortstyp0").click();
$("#korkortstyp1").click();
$("#korkortstyp2").click();
$("#korkortstyp3").click();
$("#korkortstyp4").click();
$("#korkortstyp5").click();
$("#korkortstyp6").click();
$("#korkortstyp7").click();
$("#korkortstyp8").click();
$("#korkortstyp9").click();
$("#specialist").val("Ögon.");