$("#typcheck0").click();
$("#typcheck1").click();
$("#typcheck2").click();
$("#typcheck3").click();
$("#typcheck4").click();
$("#typcheck5").click();
$("#typcheck6").click();
$("#typcheck7").click();
$("#typcheck8").click();
$("#typcheck9").click();
$("#identity2").prop("checked", true).trigger("click");
$("#synay").prop("checked", true).trigger("click");
$("#synbn").prop("checked", true).trigger("click");
$("#syncy").prop("checked", true).trigger("click");
$("#syndy").prop("checked", true).trigger("click");
$("#synen").prop("checked", true).trigger("click");
$("#synHogerOgaUtanKorrektion").val("0,0").change();
$("#synHogerOgaMedKorrektion").val("0,2").change();
$("#synHogerOgaKontaktlins").click();
$("#synVansterOgaUtanKorrektion").val("0,0").change();
$("#synVansterOgaMedKorrektion").val("0,2").change();
$("#synVasterOgaKontaktlins").click();
$("#synBinokulartUtanKorrektion").val("0,0").change();
$("#synBinokulartMedKorrektion").val("0,2").change();
$("#dioptrier").click();
$("#horselbalansay").prop("checked", true).trigger("click");
$("#horselbalansby").prop("checked", true).trigger("click");
$("#funktionsnedsattningay").prop("checked", true).trigger("click");
$("#funktionsnedsattning").val("Epilepsi").change();
$("#funktionsnedsattningbn").prop("checked", true).trigger("click");
$("#hjartkarlay").prop("checked", true).trigger("click");
$("#hjartkarlbn").prop("checked", true).trigger("click");
$("#hjartkarlcy").prop("checked", true).trigger("click");
$("#beskrivningRiskfaktorer").val("Kranskärlproblem").change();
$("#diabetesay").prop("checked", true).trigger("click");
$("#diabetestyp1").prop("checked", true).trigger("click");
$("#neurologiay").prop("checked", true).trigger("click");
$("#medvetandestorningay").prop("checked", true).trigger("click");
$("#beskrivningMedvetandestorning").val("26/6 för mycket TV-spel").change();
$("#njuraray").prop("checked", true).trigger("click");
$("#kognitivtan").prop("checked", true).trigger("click");
$("#somnvakenhetForm > span:nth-child(2) > span:nth-child(2) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(2) > input:nth-child(1)").prop("checked", true).trigger("click");
$("#narkotikalakemedela").prop("checked", true).trigger("click");
$("#narkotikaLakemedelForm > span:nth-child(2) > span:nth-child(2) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(2) > input:nth-child(1)").prop("checked", true).trigger("click");
$("#narkotikaLakemedelForm > span:nth-child(2) > span:nth-child(2) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2) > label:nth-child(3) > input:nth-child(1)").prop("checked", true).trigger("click");
$("#narkotikaLakemedelForm > span:nth-child(2) > span:nth-child(2) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(5) > td:nth-child(1) > input:nth-child(1)").prop("checked", true).trigger("click");
$("#beskrivningNarkotikalakemedel").val("Ibuprofen och många.").change();
$("#psykiskta").prop("checked", true).trigger("click");
$("#utvecklingsstorningForm > span:nth-child(2) > span:nth-child(2) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(2) > input:nth-child(1)").prop("checked", true).trigger("click");
$("#utvecklingsstorningForm > span:nth-child(2) > span:nth-child(2) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(1) > input:nth-child(1)").prop("checked", true).trigger("click");
$("#sjukhusvarda").prop("checked", true).trigger("click");
$("#tidpunkt").val("2016-09-21").change();
$("#vardinrattning").val("Smultronet").change();
$("#anledning").val("Nageltrång").change();
$("#medicineringa").prop("checked", true).trigger("click");
$("#beskrivningMedicinering").val("Alvedon.").change();
$("#kommentar").val("Inga kommentarer.").change();
$("#behorighet_bedomning").prop("checked", true).trigger("click");
$("#korkortstyp0").click();
$("#korkortstyp1").click();
$("#korkortstyp2").click();
$("#korkortstyp3").click();
$("#korkortstyp4").click();
$("#korkortstyp5").click();
$("#korkortstyp6").click();
$("#korkortstyp7").click();
$("#korkortstyp8").click();
$("#korkortstyp9").click();
$("#specialist").val("Ögon.");