$("#typcheck0").click();
$("#typcheck1").click();
$("#typcheck2").click();
$("#typcheck3").click();
$("#typcheck4").click();
$("#typcheck5").click();
$("#typcheck6").click();
$("#typcheck7").click();
$("#typcheck8").click();
$("#typcheck9").click();
$("#identity2").focus();
$("#identity2").click();
$("#identity2").focus();
$("#identity2").click();
$("#synay").focus();
$("#synay").click();
$("#synbn").focus();
$("#synbn").click();
$("#syncy").focus();
$("#syncy").click();
$("#syndy").focus();
$("#syndy").click();
$("#synen").focus();
$("#synen").click();
$("#synHogerOgaUtanKorrektion").val("0,0").change();
$("#synHogerOgaMedKorrektion").val("0,2"
$("#synHogerOgaKontaktlins").click();
$("#synVansterOgaUtanKorrektion").val("0,0").change();
$("#synVansterOgaMedKorrektion").val("0,2").change();
$("#synVasterOgaKontaktlins").click();
$("#synBinokulartUtanKorrektion").val("0,0").change();
$("#synBinokulartMedKorrektion").val("0,2").change();
$("#dioptrier").click();
$("#horselbalansay").focus().click();
/*$("#horselbalansay").click();*/
$("#horselbalansby").focus().click();
$("#funktionsnedsattningay").focus().click();
$("#funktionsnedsattning").val("Epilepsi").change();
$("#funktionsnedsattningbn").focus().click()